### PR TITLE
LUNA-29: Use types and libgamestream instead of open

### PR DESCRIPTION
**Pull request by dead**

### CODE REVIEW

**Comment by wackerl91** [comment]
@dead This is a great approach! I'll have a proper look at this next week. If this doesn't cause any problems it'll probably be part of the next update.
(And thanks for sharing this from your own project, really appreciate that!)

**Comment by dead** [comment]
Hi, Thanks! I think it will work... but be careful I didn't test it in luna.
https://github.com/dead/luna/commit/ee20b0a942e20fc952b15b2123855673cf49d5da#diff-fcb37b1de4c3890d57c280c4ead14347R26
Just be careful with this, before moonlight version 2.1.4 you could enter any pin, now I think you need to enter the right pin! (not sure thought).
And luna is great, just sad that it doesn't work in openelec (yet?)
Good luck!

**Comment by wackerl91** [comment]
Heya!
No worries, I'll have to test it either way. Thanks for the heads up regarding the pairing pin!
OpenELEC is kind of a difficult topic due to its nature of it being a really closed system, so we'd have to side load the moonlight-embedded binary. If you want to we can discuss a few options on how to make this - just shoot me an email.
Cheers!

**Comment by wackerl91** [comment]
This is now closed for good, as it's based on a really old architecture of Luna and there was no response to private messages anymore.

**Pull request closed without merging**
